 <?php

return "
DROP TABLE IF EXISTS reference_user;

CREATE TABLE reference_user (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    user_id INT UNSIGNED NOT NULL,
    description VARCHAR(150) NOT NULL,
    referee VARCHAR(50) NOT NULL,
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP 
        ON UPDATE CURRENT_TIMESTAMP
);
";